apiVersion: apps/v1
kind: Deployment
metadata:
  name: famstory-deploy
  labels:
    app: famstory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: famstory
  template:
    metadata:
      labels:
        app: famstory
    spec:
      containers:
        - name: famstory
          image: synoti21/famstory-backend:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
          - secretRef:

              name: famstory-secret
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: famstory-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: famstory-deploy
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: famstory-svc
spec:
  selector:
    app: famstory
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: famstory-route
  namespace: cicd
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`famstory.${DDNS}`)
      kind: Rule
      services:
        - name: famstory-svc
          port: 3000
  tls:
    certResolver: myresolver
