name: Node.js CI

on:
  push:
    branches: [ "main", "develop" ]
    paths-ignore:
        - 'k8s/**'

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.x

      - name: Install modules & Build
        run: |
          npm ci
          npm run build --if-present

      - name: Run test
        run: |
          npm test
          npm run test:e2e

      - name: Docker login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          logout: true

      - name: Build and push to DockerHub
        run: |
          docker build -t ${{ secrets.PROJECT_NAME }} .
          docker tag ${{ secrets.PROJECT_NAME }}:latest ${{ secrets.DOCKER_USERNAME }}/${{ secrets.PROJECT_NAME }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.PROJECT_NAME }}:latest

          
  update-manifest:
      runs-on: ubuntu-latest
      needs: CI
      steps:
        - name: Get version
          id: image
          run: |
            VERSION=$(echo ${{ github.sha }} | cut -c1-8)
            echo VERSION=$VERSION
            echo "::set-output name=version::$VERSION"
            
        - name: Setup Kustomize
          uses: imranismail/setup-kustomize@v2.1.0-rc

        - name: Checkout kustomize repository
          uses: actions/checkout@v3
          with:
            repository: Fam-Story/fam-Story_Backend
            ref: develop
            token: ${{ secrets.ACCESS_TOKEN }}
            path: fam-Story_Backend
            

        - name: Update Kubernetes resources
          run: |
            cd fam-Story_Backend/k8s/
            kustomize edit set image ${{ secrets.PROJECT_NAME }}:${{ steps.image.outputs.version }}
            cat kustomization.yaml
  
        - name: Commit and push the updated manifest
          run: |
            git config user.name 'github-actions'
            git config user.email 'github-actions@github.com'
            git add k8s/deployment.yaml
            git commit -m ":construction_worker: chore: Update deployment to ${{ github.sha }}"
            git push
