name: PR Test

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.x

      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.2.1
        with:
          host: ${{ secrets.SONAR_ENDPOINT }}
          login: ${{ secrets.SONAR_LOGIN }}
          password: ${{ secrets.SONAR_PASSWORD }}
         
      - name: Install modules & Build
        run: |
          npm ci
          npm run build --if-present

      - name: Run test
        run: |
          npm test
          npm run test:e2e

